-- Toggle WezTerm visibility (iTerm2-style "Toggle All Windows").
--   not running        -> launch
--   frontmost          -> hide (like Cmd+H)
--   running, not front -> unhide + activate
-- Invoked by the "Toggle WezTerm" macOS Quick Action
-- (generated by install-toggle-macos.sh) via osascript.

tell application "System Events"
	set wezRunning to (exists process "wezterm-gui")
end tell

if wezRunning then
	tell application "System Events"
		tell process "wezterm-gui"
			if frontmost then
				set visible to false
			else
				set visible to true
				set frontmost to true
			end if
		end tell
	end tell
else
	tell application "WezTerm" to activate
end if
